
services:
  to-do:
    build:
      context: ./to-do
      dockerfile: Dockerfile
    container_name: todo-web-app
    ports:
      - "3000:3000"
    volumes:
      - ./to-do/src:/app
    # environment:
    #   MONGO_URL: mongodb://mongo:27017/todo

  mongo:
    image: mongo:latest
    container_name: mongo-web-apps
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: